export interface ServicePageContent {
  title: string; description: string; schemaDescription: string; eyebrow: string; intro: string;
  suitableFor: string[]; implementation: string[]; workflow: string[]; validation: string[]; limitations: string[];
  faqs: { question: string; answer: string }[]; proof?: { label: string; href: string }[]; related: { label: string; href: string }[]; primaryCta?: string;
}

const contact = { label: 'Book a consultation', href: '/contact/' };

export const servicePages: Record<string, ServicePageContent> = {
  'tracking-audit': {
    title: 'Digital Analytics & Tracking Audit', description: 'A technical GA4, GTM, conversion, ecommerce, and data-quality audit with clear findings and an implementation roadmap.', schemaDescription: 'Professional digital analytics and tracking audits covering GA4, GTM, conversion tracking, data quality, and prioritised implementation roadmaps.', eyebrow: 'Technical measurement review', intro: 'A paid technical review for teams that need to understand what their measurement implementation records, misses, duplicates, or cannot reliably explain.', primaryCta: 'Request a Tracking Audit',
    suitableFor: ['A measurement setup that has changed hands or grown without clear documentation.', 'Reports, platforms, or revenue systems that disagree in ways your team cannot explain.', 'An ecommerce, consent, or advertising implementation that needs a prioritised technical review.'],
    implementation: ['GA4, GTM, event, parameter, conversion, and data-layer review.', 'Checks for missing, duplicate, or inconsistent events and observable attribution/reporting mismatches.', 'A findings register, prioritisation, QA evidence, and practical implementation roadmap.'],
    workflow: ['Define the business questions, systems, and access needed for a focused review.', 'Review instrumentation and selected data flows against the agreed scope.', 'Prioritise findings by measurement impact, implementation effort, and dependencies.', 'Hand over recommendations, validation evidence, and a route to implementation support.'],
    validation: ['Test representative journeys and compare event behaviour across intended destinations.', 'Document the evidence, assumptions, and implementation constraints behind each finding.'],
    limitations: ['It is not a legal compliance assessment or a promise that every historical discrepancy can be reconciled.', 'The free Health Check is a short self-assessment, not a crawler, source-code review, or substitute for this audit.'],
    faqs: [{question:'How is this different from the Health Check?',answer:'The Health Check uses your answers to highlight likely priorities. A Tracking Audit is a scoped professional review of the implementation and evidence available to us.'},{question:'Do you fix the findings?',answer:'The audit can stand alone or lead into implementation work. Priorities and ownership are agreed after the findings are clear.'}],
    related: [{label:'GA4 & GTM Setup',href:'/services/ga4-gtm-setup/'},{label:'Server-Side Tracking',href:'/services/server-side-tracking/'},{label:'Free Health Check',href:'/health-check/'},{label:'Case studies',href:'/case-studies/'},contact],
  },
  'server-side-tracking': {
    title: 'Server-Side Tracking (sGTM) Implementation', description: 'Implement server-side Google Tag Manager and consent-aware event forwarding with careful QA and ownership planning.', schemaDescription: 'Server-side Google Tag Manager implementation, event forwarding, deduplication, consent-aware measurement, and validation services.', eyebrow: 'Server-side measurement', intro: 'Build a controlled server-side measurement path for browser events and approved platform destinations, with consent and ownership considered from the start.',
    suitableFor: ['Browser-side tracking is fragile, difficult to govern, or needs a clearer first-party collection path.', 'Paid-media and analytics events need coordinated server-side forwarding and deduplication.', 'Your team can support the required hosting, domain, access, and ongoing operational ownership.'],
    implementation: ['Google Tag Manager Server-Side configuration and an agreed browser-to-server event path.', 'Event IDs, destination mapping, server-side forwarding, and deduplication where browser and server events coexist.', 'Consent-aware routing, access controls, and implementation documentation.'],
    workflow: ['Map the current event path, destinations, ownership, and consent boundary.', 'Design the server container, domain/hosting responsibilities, and destination configuration.', 'Implement and test representative events across browser and server paths.', 'Review diagnostics, handover details, and ongoing monitoring expectations.'],
    validation: ['Inspect event payloads and destination diagnostics for representative journeys.', 'Confirm deduplication and consent-state behaviour under agreed scenarios.'],
    limitations: ['Server-side tagging does not bypass consent, repair an unclear measurement plan, or guarantee complete data.', 'It requires ongoing ownership of hosting, domains, access, and destination changes.'],
    faqs: [{question:'Does server-side tracking replace browser tracking?',answer:'Often the two work together. The appropriate split depends on each destination, consent state, event design, and implementation constraints.'},{question:'Can it fix every attribution gap?',answer:'No. It can improve control over an agreed data path, but platform modelling, identity limits, consent choices, and upstream instrumentation still matter.'}],
    proof: [{label:'Slice server-side tracking case study',href:'/case-studies/slice/'},{label:'Roadsurfer measurement foundation case study',href:'/case-studies/roadsurfer/'}], related: [{label:'Meta Conversions API',href:'/services/meta-conversions-api/'},{label:'Tracking Audit',href:'/services/tracking-audit/'},{label:'GA4 & GTM Setup',href:'/services/ga4-gtm-setup/'},contact],
  },
  'ga4-gtm-setup': {
    title: 'GA4 & Google Tag Manager Setup', description: 'Plan and implement dependable GA4 and GTM measurement for websites, including events, data layers, QA, and documentation.', schemaDescription: 'GA4 and Google Tag Manager web implementation services including measurement planning, event taxonomy, data-layer design, QA, and documentation.', eyebrow: 'Web measurement implementation', intro: 'Create a web measurement foundation that gives teams a documented event model, governed tag management, and a clear route for validating key conversions.',
    suitableFor: ['A new website, redesign, migration, or inherited GA4/GTM setup.', 'Teams that need an agreed event taxonomy, parameters, and conversion definitions.', 'Ecommerce or multi-domain journeys where the data layer and handoffs need deliberate design.'],
    implementation: ['Measurement planning, event taxonomy, parameter definitions, and data-layer requirements.', 'GA4 property configuration, GTM container governance, and key-event/conversion setup.', 'Cross-domain requirements where applicable, debugging, documentation, and handover.'],
    workflow: ['Agree business questions, key journeys, and source-of-truth systems.', 'Define implementation requirements with developers and owners.', 'Configure GA4 and GTM, then validate representative journeys.', 'Document what is live, how it is governed, and what should be monitored.'],
    validation: ['Use browser debugging and platform tools to verify event names, parameters, and key-event behaviour.', 'Check agreed journeys for duplicate, missing, or incorrectly timed events.'],
    limitations: ['GA4/GTM setup does not make reports meaningful without clear KPI definitions and reliable upstream data.', 'Mobile or app measurement needs its own scoped implementation rather than being assumed from web tracking.'],
    faqs: [{question:'Can you remediate an existing container?',answer:'Yes, after the current setup and access model are understood. The work may include cleanup, migration, or a governed rebuild depending on the risk.'},{question:'Do you handle ecommerce events?',answer:'Yes. Ecommerce implementations are scoped around the platform, data layer, product data, and purchase lifecycle.'}],
    proof: [{label:'Roadsurfer GA4 and GTM case study',href:'/case-studies/roadsurfer/'},{label:'Slice case study',href:'/case-studies/slice/'}], related: [{label:'Ecommerce Tracking',href:'/services/ecommerce-tracking/'},{label:'Tracking Audit',href:'/services/tracking-audit/'},{label:'Server-Side Tracking',href:'/services/server-side-tracking/'},contact],
  },
  'meta-conversions-api': {
    title: 'Meta Conversions API Setup', description: 'Implement consent-aware Meta Conversions API event mapping, browser/server deduplication, diagnostics, and QA.', schemaDescription: 'Meta Conversions API setup services including event mapping, browser and server deduplication, consent-aware routing, diagnostics, and QA.', eyebrow: 'Meta measurement implementation', intro: 'Connect browser Pixel and server-side CAPI events deliberately so Meta receives usable, consent-aware signals without creating duplicate or unexplained conversions.',
    suitableFor: ['Meta advertising uses key website conversions that need a reviewed browser/server event design.', 'Duplicate, missing, or poorly matched events are visible in diagnostics or reporting.', 'Your team needs clear ownership of event mapping, consent rules, and change management.'],
    implementation: ['Browser Pixel and server-side CAPI event mapping for agreed conversion journeys.', 'Event IDs, deduplication logic, matching-data considerations, and consent-aware delivery.', 'Testing, diagnostics, and documentation for the implemented event path.'],
    workflow: ['Agree the conversion events, source systems, consent states, and ownership.', 'Map browser and server payloads and implement the selected delivery path.', 'Test representative journeys and investigate duplicate or missing-event patterns.', 'Review diagnostics and provide a maintenance handover.'],
    validation: ['Validate event names, IDs, timing, and diagnostics for representative conversion journeys.', 'Test consent-state behaviour and compare browser/server delivery against the agreed design.'],
    limitations: ['CAPI does not automatically improve ROAS or replace sound campaign strategy and measurement planning.', 'Matching quality, platform processing, consent choices, and upstream data limit what any integration can report.'],
    faqs: [{question:'Do I need server-side GTM for CAPI?',answer:'Not always. It can be one implementation route, but the right architecture depends on your stack, ownership model, and event requirements.'},{question:'Why are duplicate events a concern?',answer:'When browser and server events represent the same action, stable IDs and consistent mapping are needed so destinations can deduplicate them as intended.'}],
    related: [{label:'Server-Side Tracking',href:'/services/server-side-tracking/'},{label:'Tracking Audit',href:'/services/tracking-audit/'},{label:'GA4 & GTM Setup',href:'/services/ga4-gtm-setup/'},contact],
  },
  'ecommerce-tracking': {
    title: 'Ecommerce Tracking Implementation', description: 'Implement and validate GA4 ecommerce measurement across Shopify, WooCommerce, and custom commerce platforms.', schemaDescription: 'Ecommerce tracking implementation for Shopify, WooCommerce, and custom platforms, including GA4 ecommerce events, data layers, and QA.', eyebrow: 'Commerce measurement', intro: 'Make product, cart, checkout, and purchase measurement dependable enough to support reporting and advertising integrations—starting with the data layer and source-of-truth checks.',
    suitableFor: ['A Shopify, WooCommerce, or custom commerce journey needs a deliberate GA4 ecommerce event model.', 'Order, revenue, product, cart, or checkout data is incomplete or inconsistent.', 'Reports or advertising conversions need to be tied back to an understood purchase lifecycle.'],
    implementation: ['GA4 ecommerce events, item/product data, and data-layer requirements for the agreed platform.', 'Cart, checkout, and purchase lifecycle tracking with duplicate-purchase protection.', 'Source-of-truth comparison, advertising-platform integration where relevant, and implementation handover.'],
    workflow: ['Map the storefront, checkout path, order system, and product-data ownership.', 'Define events and item data with developers and platform owners.', 'Implement the data layer and destination configuration for representative journeys.', 'QA orders, revenue, item data, and duplicate protections before handover.'],
    validation: ['Test product-to-purchase journeys and compare selected values with the agreed source of truth.', 'Check order identifiers, revenue fields, item arrays, and retry/refresh behaviours for duplication.'],
    limitations: ['A dashboard cannot repair unreliable upstream product or order instrumentation.', 'Platform customisations, payment flows, and consent configurations can affect what is technically available to measure.'],
    faqs: [{question:'Do you support Shopify and WooCommerce?',answer:'Yes, alongside custom platforms. The technical scope depends on the checkout, plugins, data availability, and control of the data layer.'},{question:'Can you guarantee order totals will match everywhere?',answer:'No. We validate the agreed measurement path and document known differences, but systems can apply different processing, timing, currencies, and attribution rules.'}],
    proof: [{label:'Roadsurfer ecommerce measurement case study',href:'/case-studies/roadsurfer/'},{label:'Slice measurement case study',href:'/case-studies/slice/'}], related: [{label:'GA4 & GTM Setup',href:'/services/ga4-gtm-setup/'},{label:'Analytics Dashboards',href:'/services/analytics-dashboards/'},{label:'Tracking Audit',href:'/services/tracking-audit/'},contact],
  },
  'analytics-dashboards': {
    title: 'Analytics Dashboards & Reporting', description: 'Design decision-focused analytics dashboards and reporting with clear KPI definitions, source integration, QA, and governance.', schemaDescription: 'Analytics dashboards and reporting services including KPI definition, Looker Studio, source integration, metric governance, and quality assurance.', eyebrow: 'Reporting foundations', intro: 'Turn agreed measurement and business questions into usable reporting, with explicit metric definitions, source ownership, and QA rather than a generic collection of charts.',
    suitableFor: ['Teams need a shared view of agreed KPIs across analytics, commerce, or advertising sources.', 'Existing reports are difficult to trust because definitions, freshness, or ownership are unclear.', 'Stakeholders need reporting views that reflect their decisions without losing metric governance.'],
    implementation: ['KPI definition, source mapping, and stakeholder-specific dashboard architecture.', 'Looker Studio and, where appropriate, BigQuery or other agreed source integrations.', 'Metric definitions, data freshness expectations, governance, documentation, and automated reporting workflows.'],
    workflow: ['Agree the decisions, users, KPIs, and source systems the reporting must support.', 'Define metric logic, ownership, freshness, and visual hierarchy before building.', 'Build dashboard views and validate selected metrics with data owners.', 'Document definitions and a maintenance process for source or business changes.'],
    validation: ['Reconcile representative dashboard figures to agreed source data and document expected timing differences.', 'Review filters, permissions, refresh behaviour, and stakeholder usability before handover.'],
    limitations: ['Dashboards cannot repair incorrect upstream measurement; a Tracking Audit, GA4/GTM, or ecommerce implementation may need to come first.', 'Data freshness depends on the source systems and connectors, so it should be agreed rather than assumed to be real time.'],
    faqs: [{question:'Can you build a dashboard from any source?',answer:'We scope integrations around available access, connector constraints, data quality, and metric definitions before promising a reporting outcome.'},{question:'Should we start with a dashboard?',answer:'If source tracking is unreliable, start with an audit or measurement implementation. Reporting is most useful once the input data has a clear foundation.'}],
    related: [{label:'Tracking Audit',href:'/services/tracking-audit/'},{label:'Ecommerce Tracking',href:'/services/ecommerce-tracking/'},{label:'GA4 & GTM Setup',href:'/services/ga4-gtm-setup/'},contact],
  },
};
