import { ButtonLink } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Activity, ArrowRight, BarChart3, CheckCircle2, Database, FileSearch, Lock, Server, Smartphone, TrendingUp, Zap } from "lucide-react";
import TechnologyGrid from "@/components/TechnologyGrid";

const groups = [
  { id: "measurement-implementation", title: "Measurement Implementation", description: "Build reliable measurement across websites, apps and server-side systems.", services: [
    { title: "GA4/GTM Setup", description: "Measurement planning, data-layer design, Google Analytics 4 and Google Tag Manager implementation for websites and web applications.", bullets: ["Measurement plans and event taxonomy", "Data-layer requirements", "GA4 events and parameters", "GTM tags, triggers and variables", "Ecommerce and funnel measurement", "Conversion definitions", "Cross-domain measurement where applicable", "QA and documentation"], who: "Teams implementing or improving website measurement", href: "/services/ga4-gtm-setup/", icon: BarChart3 },
    { title: "Server-Side Tracking", description: "Design a controlled server-side event path across web, app and backend sources.", bullets: ["Server-side GTM architecture", "Consent-aware event routing", "Destination integrations", "Deduplication and QA"], who: "Teams with multi-destination or server event requirements", href: "/services/server-side-tracking/", icon: Server },
    { title: "Mobile Analytics", description: "Mobile product analytics implementation across Firebase Analytics, Amplitude, Mixpanel, PostHog and other supported platforms.", bullets: ["Governed mobile event architecture", "User and event properties", "Funnels and product journeys", "Retention and cohort measurement", "Identity and lifecycle measurement", "Advanced analytics features where supported", "SDK and data-quality QA"], who: "Product teams that need to understand behavior inside their apps", href: "/services/mobile-analytics/", icon: Smartphone },
  ]},
  { id: "attribution-privacy", title: "Attribution & Privacy", description: "Connect campaign measurement and consent-aware data collection across mobile and digital platforms.", services: [
    { title: "Mobile Measurement", description: "Mobile measurement and MMP implementation across AppsFlyer, Adjust, Branch, Kochava and other supported attribution platforms.", bullets: ["Acquisition attribution", "Install, reinstall and re-engagement measurement", "In-app conversion events", "Deep and deferred deep linking", "Ad-network integrations", "iOS privacy-era measurement", "Partner postbacks, raw-data and API integrations", "Revenue measurement and attribution QA"], who: "Apps measuring campaign-driven installs and downstream outcomes", href: "/services/mobile-measurement/", icon: Zap },
    { title: "Meta Conversions API", description: "Server-side conversion event delivery with event mapping, diagnostics and deduplication.", bullets: ["Event mapping", "Browser/server deduplication", "Consent-aware implementation", "Diagnostics and QA"], who: "Teams implementing Meta conversion measurement", href: "/services/meta-conversions-api/", icon: Activity },
    { title: "Cookie Consent & CMP", description: "Consent management platform integration and consent-aware tag behavior.", bullets: ["CMP integration", "Consent Mode configuration", "Tag consent requirements", "Regional behavior QA"], who: "Teams aligning measurement behavior with consent requirements", href: "/services/cookie-consent/", icon: Lock },
  ]},
  { id: "strategy-quality-reporting", title: "Strategy, Quality & Reporting", description: "Plan measurement, assess implementation quality and turn trusted data into decision-ready reporting.", services: [
    { title: "Measurement Planning & Architecture Design", description: "Define the measurement model, event architecture, data flows, systems, integrations and implementation roadmap before development begins.", bullets: ["Align measurement with business objectives", "Define KPIs and source-of-truth systems", "Design event and identity architecture", "Map complete data flows", "Evaluate technology and integration options", "Give developers implementation-ready requirements"], who: "Teams planning a new or changing measurement stack", href: "/services/measurement-planning/", icon: Database },
    { title: "Tracking Audit", description: "Review implementation quality, data flows and measurement gaps, with prioritized remediation guidance.", bullets: ["Technical configuration review", "Event and payload validation", "Data-quality findings", "Remediation priorities"], who: "Teams reviewing an existing analytics setup", href: "/services/tracking-audit/", icon: FileSearch },
    { title: "Analytics Dashboards & Reporting", description: "Connect analytics and business metrics in reporting designed around team decisions.", bullets: ["KPI definitions", "Source and metric mapping", "Dashboard design", "Reconciliation and documentation"], who: "Teams that need consistent reporting across sources", href: "/services/analytics-dashboards/", icon: TrendingUp },
  ]},
];

export default function Services() {
  return <div className="min-h-screen flex flex-col">
    <section className="pt-32 pb-16 md:pt-40 md:pb-24"><div className="container"><div className="max-w-4xl mx-auto text-center"><h1 className="heading-xl mb-6">Analytics, Tracking &amp; Measurement <span className="text-primary">Services</span></h1><p className="body-lg text-muted-foreground mb-8">Plan and implement dependable measurement across web, mobile and server-side systems, with clear ownership, validation and reporting.</p><div className="flex flex-col sm:flex-row gap-4 justify-center"><ButtonLink href="/contact/" size="lg" className="text-base px-8 h-12">Get Free Consultation <ArrowRight className="ml-2 h-5 w-5" /></ButtonLink><ButtonLink href="/health-check/" size="lg" variant="outline">Free Health Check</ButtonLink></div></div></div></section>
    {groups.map((group, index) => <section key={group.id} id={group.id} className={`section-spacing ${index % 2 === 0 ? "bg-muted/30" : ""}`}><div className="container"><div className="max-w-3xl mx-auto text-center mb-12"><h2 className="heading-md mb-4">{group.title}</h2><p className="body-md text-muted-foreground">{group.description}</p></div><div className="grid gap-6 max-w-6xl mx-auto">{group.services.map((service) => { const Icon = service.icon; return <Card key={service.href} id={service.href.split("/").filter(Boolean).at(-1)} className="hover:border-primary transition-colors"><CardContent className="p-6 md:p-8"><div className="grid gap-6 md:grid-cols-[1fr_1.2fr_.8fr] md:gap-8"><div><div className="mb-4 p-3 rounded-lg bg-primary/10 inline-block"><Icon className="h-7 w-7 text-primary" /></div><h3 className="text-xl md:text-2xl font-semibold mb-3">{service.title}</h3><p className="text-sm text-muted-foreground">{service.description}</p></div><div><h4 className="font-semibold mb-3 text-sm uppercase tracking-wide text-muted-foreground">Scope</h4><ul className="grid gap-2 sm:grid-cols-2">{service.bullets.map((item) => <li key={item} className="flex items-start gap-2 text-sm"><CheckCircle2 className="h-4 w-4 text-primary mt-0.5 shrink-0" /><span>{item}</span></li>)}</ul></div><div><h4 className="font-semibold mb-3 text-sm uppercase tracking-wide text-muted-foreground">Who needs this</h4><p className="text-sm text-muted-foreground mb-4">{service.who}</p><ButtonLink href={service.href} size="sm" className="w-full">Explore {service.title}</ButtonLink></div></div></CardContent></Card>; })}</div></div></section>)}
    <section className="section-spacing"><div className="container"><div className="max-w-3xl mx-auto text-center mb-12"><h2 className="heading-md mb-6">Technologies We Work With</h2><p className="body-md text-muted-foreground">Tools are selected around the measurement requirements, existing systems and implementation constraints.</p></div><h3 className="text-center font-semibold mb-4">Web &amp; Server</h3><TechnologyGrid keys={["googleAnalytics", "googleTagManager", "serverSideGtm", "metaCapi"]} /><h3 className="text-center font-semibold mt-10 mb-4">Mobile Analytics</h3><TechnologyGrid keys={["firebaseAnalytics", "amplitude", "mixpanel", "posthog"]} /><h3 className="text-center font-semibold mt-10 mb-4">Mobile Measurement</h3><TechnologyGrid keys={["appsflyer", "adjust", "branch", "kochava"]} /><h3 className="text-center font-semibold mt-10 mb-4">Data &amp; Reporting</h3><TechnologyGrid keys={["lookerStudio", "bigQuery", "powerBi", "snowflake"]} /></div></section>
    <section className="section-spacing bg-muted/30"><div className="container"><Card className="border-2 border-primary"><CardContent className="p-8 md:p-12 text-center"><h2 className="heading-md mb-6">Not Sure Which Service You Need?</h2><p className="body-md text-muted-foreground mb-8 max-w-2xl mx-auto">We can review your current measurement setup and help define a practical next step.</p><ButtonLink href="/contact/" size="lg">Get Free Consultation <ArrowRight className="ml-2 h-5 w-5" /></ButtonLink></CardContent></Card></div></section>
  </div>;
}
